### ISSUE TITLE
Release datamodel 2.0.0

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/datamodel#93]
- [ ] Write changelog entries
- [ ] Bump up version 2.0.0 in setup.cfg
- [ ] Add a git tag for the release 
- [ ] Make a GitHub release
